export const productdata = [
  {
    image: "https://example.com/clothing1.jpg",
    title: "Men's Casual Shirt",
    title2: "Stylish Blue Shirt for Men",
    color: "Blue",
    selling_price: "$29.99",
    price: "$39.99",
    discount: "25% off",
  },
  {
    image: "https://example.com/clothing2.jpg",
    title: "Women's Floral Dress",
    title2: "Elegant Pink Floral Dress",
    color: "Pink",
    selling_price: "$39.99",
    price: "$49.99",
    discount: "20% off",
  },
  {
    image: "https://example.com/clothing3.jpg",
    title: "Men's Classic Trousers",
    title2: "Black Formal Trousers for Men",
    color: "Black",
    selling_price: "$49.99",
    price: "$59.99",
    discount: "17% off",
  },
  {
    image: "https://example.com/clothing4.jpg",
    title: "Women's Summer Blouse",
    title2: "Light Yellow Summer Blouse",
    color: "Yellow",
    selling_price: "$19.99",
    price: "$29.99",
    discount: "33% off",
  },
  {
    image: "https://example.com/clothing5.jpg",
    title: "Men's Denim Jacket",
    title2: "Classic Blue Denim Jacket",
    color: "Blue",
    selling_price: "$59.99",
    price: "$79.99",
    discount: "25% off",
  },
  {
    image: "https://example.com/clothing6.jpg",
    title: "Women's Striped T-shirt",
    title2: "Black and White Striped Tee",
    color: "Black/White",
    selling_price: "$24.99",
    price: "$29.99",
    discount: "17% off",
  },
  {
    image: "https://example.com/clothing7.jpg",
    title: "Men's Formal Suit",
    title2: "Charcoal Gray Formal Suit",
    color: "Charcoal Gray",
    selling_price: "$149.99",
    price: "$179.99",
    discount: "16% off",
  },
  {
    image: "https://example.com/clothing8.jpg",
    title: "Women's Leather Jacket",
    title2: "Stylish Brown Leather Jacket",
    color: "Brown",
    selling_price: "$79.99",
    price: "$99.99",
    discount: "20% off",
  },
  {
    image: "https://example.com/clothing9.jpg",
    title: "Men's Sports Shorts",
    title2: "Comfortable Gray Sports Shorts",
    color: "Gray",
    selling_price: "$19.99",
    price: "$24.99",
    discount: "20% off",
  },
  {
    image: "https://example.com/clothing10.jpg",
    title: "Women's Denim Jeans",
    title2: "Classic Indigo Denim Jeans",
    color: "Indigo",
    selling_price: "$34.99",
    price: "$44.99",
    discount: "22% off",
  },
];
